### ISSUE TITLE
Farmer's Delight Update Broke cutting board recipes

### ISSUE THREAD

**Issue by Akitori** [justKaisa/farmersdelightintegrations#1]
The newest update broke all the recipes for cutting boards/using cutting boards. Just letting you know

**Comment by justKaisa** [comment]
Appreciate the interest, I'm fully aware of the update. It didn't break anything, as it doesn't apply to knives :)

**Comment by Akitori** [comment]
Err, it does apply to knives. I just checked. Filets/stuff from aquaculture aren't working currently.

**Comment by justKaisa** [comment]
That may be because you aren't using a fillet knife

**Comment by Akitori** [comment]
Right, I got a filet knife, put it on cutting board and attempted to use it for filet, didn't work

![2021-03-25_17 56 36](https://user-images.githubusercontent.com/24502131/112554118-b3baba00-8d93-11eb-8936-7b1e6b96b89c.png)
![2021-03-25_17 56 48](https://user-images.githubusercontent.com/24502131/112554126-b74e4100-8d93-11eb-9360-21f67db43f4e.png)
![2021-03-25_17 58 12](https://user-images.githubusercontent.com/24502131/112554130-b9b09b00-8d93-11eb-9d21-df98bd6d7277.png)

Most of the cutting board recipes are default recipes for farmer's delight

**Comment by justKaisa** [comment]
Ok, that's quite odd. I do not have the same issue at all.
![image](https://user-images.githubusercontent.com/35191521/112554562-d7e3be80-8dc6-11eb-97d5-e67ac760d762.png)
Make sure you have all your mods up to date and to rule out all other possible causes. Reinstall the mod, maybe...

**Comment by justKaisa** [comment]
There really isn't a way for it to work for me but not for you

**Comment by Akitori** [comment]
corrupted download, on my end.

my bad
